
# Cache fonts for 3 weeks (1814400 seconds = 3 weeks)
[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=1814400"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=1814400"

[[headers]]
  for = "*.ttf"
  [headers.values]
    Cache-Control = "public, max-age=1814400"

[[headers]]
  for = "*.otf"
  [headers.values]
    Cache-Control = "public, max-age=1814400"
